### ISSUE TITLE
Doesn't work on Unreal Engine 5.3

### ISSUE THREAD

**Issue by joshuarobs** [PreyK/Unreal-Minimal-Viable-Flecs#3]
I downloaded this project, then I tried to open it in UE 5.3, it said it's a 5.1 project, so I opened a copy of that original as it suggested, then it says ````FlecsLibrary```` and ````FlecsTest```` are missing or built with a different engine, so I press "Yes" to rebuild them.

Then I get a popup saying ````FlecsTest could not be compiled. Try rebuilding from source manually.```` I press ok, and nothing happens.

Am I missing something here? I'm new to Unreal Engine and new to Flecs

**Comment by joshuarobs** [comment]
Credit to [Megafunk ](https://github.com/Megafunk) from the Flecs discord for this solution

You have to do some changes to the code because its using outdated removed API regarding the Ticker

FlecsTest > FlecsSubsystem.h | Line #63
`
From: FDelegateHandle OnTickHandle;
`
`
To: FTSTicker::FDelegateHandle OnTickHandle;
`

FlecsTest > FlecsSubsystem.cpp | Line #6
`
From: OnTickHandle = FTicker::GetCoreTicker().AddTicker(OnTickDelegate);
`
`
To: OnTickHandle = FTSTicker::GetCoreTicker().AddTicker(OnTickDelegate);
`

FlecsTest > FlecsSubsystem.cpp | Line #64
`
From: FTicker::GetCoreTicker().RemoveTicker(OnTickHandle);
`
`
To: FTSTicker::GetCoreTicker().RemoveTicker(OnTickHandle);
`

Would be good if someone were to make the pull request since idk how to do it myself

**Comment by PreyK** [comment]
Thanks for the report!
Just ran into this myself as I'm upgrading my projects to 5.3
Will make an update soon.

**Comment by PreyK** [comment]
Fixed, feel free to reopen this if you experience 5.3 related issues.
