### ISSUE TITLE
After porting to 5.3, and running the game in editor, when you quit game, your error log is spammed with errors

### ISSUE THREAD

**Issue by joshuarobs** [PreyK/Unreal-Minimal-Viable-Flecs#5]
I ported to 5.3, then run the game in the editor, **pick up the gun**, and when I quit the game, the error log is spammed with this:
````
Blueprint Runtime Error: "Accessed None trying to read property EntityRef". Node:  Highlight Entity Graph:  EventGraph Function:  Execute Ubergraph BP Weapon Component Blueprint:  BP_Weapon_Component
````

**Comment by PreyK** [comment]
https://github.com/PreyK/Unreal-Minimum-Viable-Flecs/commit/ac7bcf89b3226d13b7e91c446c172b9bdc7acb55
Fixes this.
If you manually updated the project to 5.3, you need to replace the get on the entityref variable to a validated get in the BP_WeaponComponent like so:
![image](https://github.com/PreyK/Unreal-Minimum-Viable-Flecs/assets/1968543/3010c268-765f-4da8-99d5-66566fab0252)

![image](https://github.com/PreyK/Unreal-Minimum-Viable-Flecs/assets/1968543/1f2fc714-604f-485f-94f4-8da9a74c8a7a)

**Comment by joshuarobs** [comment]
I fixed it by just redownloading your latest version, thanks
